%% Auto-generated by nft_gen.escript from nf_tables.h.
%% Do not edit -- re-run: make gen

-ifndef(NFT_CONSTANTS_HRL).
-define(NFT_CONSTANTS_HRL, true).

%% === Netfilter verdicts (from linux/netfilter.h, stable ABI) ===
-define(NF_DROP,    0).
-define(NF_ACCEPT,  1).

%% === Netfilter hooks (from linux/netfilter.h, stable ABI) ===
-define(NF_INET_PRE_ROUTING,  0).
-define(NF_INET_LOCAL_IN,     1).
-define(NF_INET_FORWARD,      2).
-define(NF_INET_LOCAL_OUT,    3).
-define(NF_INET_POST_ROUTING, 4).

%% === nft_registers ===
-define(NFT_REG_VERDICT, 0).
-define(NFT_REG_1, 1).
-define(NFT_REG_2, 2).
-define(NFT_REG_3, 3).
-define(NFT_REG_4, 4).
-define(NFT_REG32_00, 8).
-define(NFT_REG32_01, 9).
-define(NFT_REG32_02, 10).
-define(NFT_REG32_03, 11).
-define(NFT_REG32_04, 12).
-define(NFT_REG32_05, 13).
-define(NFT_REG32_06, 14).
-define(NFT_REG32_07, 15).
-define(NFT_REG32_08, 16).
-define(NFT_REG32_09, 17).
-define(NFT_REG32_10, 18).
-define(NFT_REG32_11, 19).
-define(NFT_REG32_12, 20).
-define(NFT_REG32_13, 21).
-define(NFT_REG32_14, 22).
-define(NFT_REG32_15, 23).

%% === nft_verdicts ===
-define(NFT_CONTINUE, 16#FFFFFFFF).
-define(NFT_BREAK, 16#FFFFFFFE).
-define(NFT_JUMP, 16#FFFFFFFD).
-define(NFT_GOTO, 16#FFFFFFFC).
-define(NFT_RETURN, 16#FFFFFFFB).

%% === nft_cmp_ops ===
-define(NFT_CMP_EQ, 0).
-define(NFT_CMP_NEQ, 1).
-define(NFT_CMP_LT, 2).
-define(NFT_CMP_LTE, 3).
-define(NFT_CMP_GT, 4).
-define(NFT_CMP_GTE, 5).

%% === nft_range_ops ===
-define(NFT_RANGE_EQ, 0).
-define(NFT_RANGE_NEQ, 1).

%% === nft_lookup_flags ===
-define(NFT_LOOKUP_F_INV, 1).

%% === nft_payload_bases ===
-define(NFT_PAYLOAD_LL_HEADER, 0).
-define(NFT_PAYLOAD_NETWORK_HEADER, 1).
-define(NFT_PAYLOAD_TRANSPORT_HEADER, 2).
-define(NFT_PAYLOAD_INNER_HEADER, 3).
-define(NFT_PAYLOAD_TUN_HEADER, 4).

%% === nft_meta_keys ===
-define(NFT_META_LEN, 0).
-define(NFT_META_PROTOCOL, 1).
-define(NFT_META_PRIORITY, 2).
-define(NFT_META_MARK, 3).
-define(NFT_META_IIF, 4).
-define(NFT_META_OIF, 5).
-define(NFT_META_IIFNAME, 6).
-define(NFT_META_OIFNAME, 7).
-define(NFT_META_IFTYPE, 8).
-define(NFT_META_OIFTYPE, 9).
-define(NFT_META_SKUID, 10).
-define(NFT_META_SKGID, 11).
-define(NFT_META_NFTRACE, 12).
-define(NFT_META_RTCLASSID, 13).
-define(NFT_META_SECMARK, 14).
-define(NFT_META_NFPROTO, 15).
-define(NFT_META_L4PROTO, 16).
-define(NFT_META_BRI_IIFNAME, 17).
-define(NFT_META_BRI_OIFNAME, 18).
-define(NFT_META_PKTTYPE, 19).
-define(NFT_META_CPU, 20).
-define(NFT_META_IIFGROUP, 21).
-define(NFT_META_OIFGROUP, 22).
-define(NFT_META_CGROUP, 23).
-define(NFT_META_PRANDOM, 24).
-define(NFT_META_SECPATH, 25).
-define(NFT_META_IIFKIND, 26).
-define(NFT_META_OIFKIND, 27).
-define(NFT_META_BRI_IIFPVID, 28).
-define(NFT_META_BRI_IIFVPROTO, 29).
-define(NFT_META_TIME_NS, 30).
-define(NFT_META_TIME_DAY, 31).
-define(NFT_META_TIME_HOUR, 32).
-define(NFT_META_SDIF, 33).
-define(NFT_META_SDIFNAME, 34).
-define(NFT_META_BRI_BROUTE, 35).
-define(NFT_META_BRI_IIFHWADDR, 36).

%% === nft_ct_keys ===
-define(NFT_CT_STATE, 0).
-define(NFT_CT_DIRECTION, 1).
-define(NFT_CT_STATUS, 2).
-define(NFT_CT_MARK, 3).
-define(NFT_CT_SECMARK, 4).
-define(NFT_CT_EXPIRATION, 5).
-define(NFT_CT_HELPER, 6).
-define(NFT_CT_L3PROTOCOL, 7).
-define(NFT_CT_SRC, 8).
-define(NFT_CT_DST, 9).
-define(NFT_CT_PROTOCOL, 10).
-define(NFT_CT_PROTO_SRC, 11).
-define(NFT_CT_PROTO_DST, 12).
-define(NFT_CT_LABELS, 13).
-define(NFT_CT_PKTS, 14).
-define(NFT_CT_BYTES, 15).
-define(NFT_CT_AVGPKT, 16).
-define(NFT_CT_ZONE, 17).
-define(NFT_CT_EVENTMASK, 18).
-define(NFT_CT_SRC_IP, 19).
-define(NFT_CT_DST_IP, 20).
-define(NFT_CT_SRC_IP6, 21).
-define(NFT_CT_DST_IP6, 22).
-define(NFT_CT_ID, 23).

%% === nft_limit_type ===
-define(NFT_LIMIT_PKTS, 0).
-define(NFT_LIMIT_PKT_BYTES, 1).

%% === nft_limit_flags ===
-define(NFT_LIMIT_F_INV, 1).

%% === nft_reject_types ===
-define(NFT_REJECT_ICMP_UNREACH, 0).
-define(NFT_REJECT_TCP_RST, 1).
-define(NFT_REJECT_ICMPX_UNREACH, 2).

%% === nft_reject_inet_code ===
-define(NFT_REJECT_ICMPX_NO_ROUTE, 0).
-define(NFT_REJECT_ICMPX_PORT_UNREACH, 1).
-define(NFT_REJECT_ICMPX_HOST_UNREACH, 2).
-define(NFT_REJECT_ICMPX_ADMIN_PROHIBITED, 3).

%% === nft_nat_types ===
-define(NFT_NAT_SNAT, 0).
-define(NFT_NAT_DNAT, 1).

%% === Object types (#define, from nf_tables.h) ===
-define(NFT_OBJECT_COUNTER, 1).
-define(NFT_OBJECT_QUOTA, 2).
-define(NFT_OBJECT_CT_HELPER, 3).
-define(NFT_OBJECT_LIMIT, 4).
-define(NFT_OBJECT_CONNLIMIT, 5).
-define(NFT_OBJECT_TUNNEL, 6).
-define(NFT_OBJECT_CT_TIMEOUT, 7).
-define(NFT_OBJECT_SECMARK, 8).
-define(NFT_OBJECT_CT_EXPECT, 9).
-define(NFT_OBJECT_SYNPROXY, 10).

-endif. %% NFT_CONSTANTS_HRL
